name: mybot
services:
  app:
    build:
      dockerfile: Dockerfile
    resources:
      cpu: 1
      memory: 512
    domains:
      - mybot.laravel.app
    webserver:
      nginx:
        inline_config: |
          root /var/www/html/public;

          location / {
              try_files $uri $uri/ /index.php?$query_string;
          }
    env:
      APP_ENV: production
      APP_KEY: base64:xxx # заменим позже
      LOG_CHANNEL: stderr
      DB_CONNECTION: pgsql
      DB_HOST: ${NEON_DB_HOST}
      DB_PORT: 5432
      DB_DATABASE: neondb
      DB_USERNAME: ${NEON_DB_USERNAME}
      DB_PASSWORD: ${NEON_DB_PASSWORD}
      
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: predis
      REDIS_URL: ${UPSTASH_REDIS_URL}
      REDIS_TOKEN: ${UPSTASH_REDIS_TOKEN}