# Простая конфигурация Nginx для обслуживания SPA
location / {
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;" always;
    try_files $uri $uri/ /index.php?$query_string;
}

# MIME-типы для JavaScript файлов
location ~* \.js$ {
    add_header Content-Type text/javascript;
}

# MIME-типы для CSS файлов
location ~* \.css$ {
    add_header Content-Type text/css;
}

# MIME-типы для webmanifest файлов
location ~* \.webmanifest$ {
    add_header Content-Type application/manifest+json;
}
