# Основной маршрут для Laravel
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

# Простые правила для медиа-типов

# JavaScript файлы
location ~* \.js$ {
    add_header Content-Type "text/javascript";
}

# CSS файлы
location ~* \.css$ {
    add_header Content-Type "text/css";
}

# WebManifest файлы
location ~* \.webmanifest$ {
    add_header Content-Type "application/manifest+json";
}

# Изображения
location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
    expires 30d;
}
